### ISSUE TITLE
Possible bug in CuI derivation?

### ISSUE THREAD

**Issue by bmcfee** [MrChrisJohnson/implicit-mf#1]
The per-user/per-item inner loop code does not appear to match the update equations (4) and (5) given in HKV2008.

Specifically, this block: https://github.com/bmcfee/implicit-mf/blob/master/mf.py#L75-L79

``` python
CuI = sparse.diags(counts_i, [0])
pu = counts_i.copy()
pu[np.where(pu != 0)] = 1.0
YTCuIY = fixed_vecs.T.dot(CuI).dot(fixed_vecs)
YTCupu = fixed_vecs.T.dot(CuI + eye).dot(sparse.csr_matrix(pu).T)
```

would match the paper if `CuI` had the identity subtracted off:

``` python
CuI = sparse.diags(counts_i, [0]) - eye
```

Or am I missing something clever here?

**Comment by alexeygrigorev** [comment]
Interestingly, when I change `+ eye` to `- eye` in line 79, my validation metrics improves
