### ISSUE TITLE
Very fast ALS on GPUs

### ISSUE THREAD

**Issue by wei-tan** [MrChrisJohnson/implicit-mf#4]
Hi Chris, I have been following your work on using MF to recommend music, great work!
We have an extremely fast ALS implementation on GPUs: https://github.com/wei-tan/CuMF/ . It is an order or magnitude faster than Spark ALS. 

For now we do not support implicit-mf but it would be straightforward to add that. Maybe you find this interesting to you.
Thanks,
Wei

**Comment by MrChrisJohnson** [comment]
Nice! Thanks for sharing, I'll check it out.

**Comment by MrChrisJohnson** [comment]
Closing since this isn't actually an issue.
